version: "3"

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - database
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
